// Copyright 2017-2025 @pezkuwi/vanitygen authors & contributors
// SPDX-License-Identifier: Apache-2.0

// Do not edit, auto-generated by @pezkuwi/dev

export const packageInfo = { name: '@pezkuwi/vanitygen', path: 'auto', type: 'auto', version: '1.0.0' };
